# Generated by Django 5.0.1 on 2024-01-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(null=True)),
                ('loan_amount', models.BigIntegerField(null=True)),
                ('tenure', models.IntegerField(null=True)),
                ('interest_rate', models.IntegerField(null=True)),
                ('monthly_payment', models.IntegerField(null=True)),
                ('EMI_on_Time', models.IntegerField(null=True)),
                ('approvel_date', models.CharField(max_length=255, null=True)),
                ('end_date', models.CharField(max_length=255, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
