# Generated by Django 5.0.1 on 2024-01-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_loan_created_on_alter_loan_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
