# Generated by Django 5.0.1 on 2024-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_customer_id_loan_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approvel_date',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='end_date',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
